fazlashop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('shop.urls')),
    path('django_admin/', admin.site.urls),
]

shop/urls.py
from django.urls import path
from . import views

app_name = "shop"
urlpatterns = [
    # /shop/
    path('', views.IndexView.as_view(), name='index'),

]

shop/models.py
from email.mime import image
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
# Create your models here.


class Shop(models.Model):
    name = models.CharField(max_length=200)
    created_date = models.DateTimeField(default=timezone.now)
    description = models.TextField(null=True)
    image = models.ImageField(null=True, upload_to="shops")
    def __str__(self):
        return self.name


class FavoriteShop(models.Model):
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class Product(models.Model):
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    created_date = models.DateTimeField(default=timezone.now)
    description = models.TextField(null=True)
    image = models.ImageField(null=True, upload_to="products")
    def __str__(self):
        return self.name


class FavoriteProduct(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

shop/views.py
from django.shortcuts import render
from django.http import Http404, HttpResponse, HttpResponseRedirect
# Create your views here.
from django.views import generic
from .models import Product, Shop
from django.utils import timezone

class IndexView(generic.ListView):
    template_name = 'shop/index.html'
    context_object_name = 'newest_shops'

    def get_queryset(self):
        return Shop.objects.order_by('-created_date')[:5]

def create_shop(request):
    created_date = request.POST['created_date'] if request.POST['created_date'] else timezone.now()
    try:
        shop_name = request.POST['shop_name']
        shop = Shop.objects.create(shop_name,created_date)
        shop.save()    
        return HttpResponse("Successful")
    except:
        return render(request, 'shop/index.html', {
            'shop' : shop,
            'error_message' : "An error occurred."
        })        

shop/templates/shop/index.html
{% extends 'shop/shop_template.html' %}

{% block title %}
    FazlaShop Main Page
{% endblock title %}

{% block content %}
    <ul>
    {% for shop in newest_shops %}
        <li>{{ shop.name }} - {{ shop.created_date }}</li>
    {% endfor %}
{% endblock content %}

shop/templates/shop/shop_template.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <div class="wrapper">
        <div class="navigation">
            <nav class="navbar navbar-expand-lg bg-dark navbar-dark">
                <div class="container-fluid">
                    <a class="navbar-brand" href="{% url 'shop:index' %}">FazlaShop</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                      </button>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav">
                            {% url 'shop:index' as url %}
                            <li class="nav-item">
                                <a class="nav-link {% if request.path == url %}active{% endif %}" aria-current="page" href="{% url 'shop:index' %}">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link {% if request.path == url %}active{% endif %}" href="">Shops</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link {% if request.path == url %}active{% endif %}" href="#">Products</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
        <div class="content">
            <div class="container">
                {% block content %}{% endblock %}
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</body>

</html>